### ISSUE TITLE
Which version of Python should I use?

### ISSUE THREAD

**Issue by tomasruffo** [pnkvalavala/digitaltwin#1]
I am having issues with the installation

**Comment by pnkvalavala** [comment]
**For Google Colab:**

It usually comes preconfigured with Python 3.10.12. You can check the Python version in your Colab notebook by running:

   ```python
   !python --version
   ```

**For Local Machine:**

To run the `streamlit run app.py` command on your local machine, you need to make sure that Streamlit is installed. You can install Streamlit using `pip` with the following command:

```bash
pip install streamlit
```

After installing Streamlit, you should be able to run the Streamlit application locally without any issues.

If you encounter any other issues during the installation or have additional questions, please provide more details about the specific problem you're facing, and we'll be happy to assist you further.

Feel free to reach out if you need more help or have any other questions regarding this project.

**Comment by pnkvalavala** [comment]
It seems that your issue has been resolved. If you encounter any more problems or have further questions in the future, please don't hesitate to reach out.

I'm marking this issue as closed for now. If you need any additional help, feel free to create a new issue, and we'll be here to assist you.

Thank you for using our project, and we hope you have a great experience with it! 😊
